namespace RestoranMenu
{
    partial class PageMain
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(PageMain));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges19 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges20 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges21 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges22 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges23 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges24 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges25 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges26 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges27 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.pnlHeadBar = new System.Windows.Forms.Panel();
            this.lblYonetimBar = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.pnlMain = new System.Windows.Forms.Panel();
            this.pnlLastOrders = new Bunifu.UI.WinForms.BunifuPanel();
            this.pnlLeft = new Bunifu.UI.WinForms.BunifuPanel();
            this.btnSepet = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnEtYemekleri = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnMakarnalar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnCorbalar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnSebzeYemekleri = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnIcecekler = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnSalatalar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnTatlilar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pnlLeftImage = new Bunifu.UI.WinForms.BunifuPanel();
            this.pbLogo = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.pnlTopColorBar = new Bunifu.UI.WinForms.BunifuPanel();
            this.btnExit = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.dragControlHeadBar = new Bunifu.Framework.UI.BunifuDragControl(this.components);
            this.dragControlLogo = new Bunifu.Framework.UI.BunifuDragControl(this.components);
            this.dragControlResim = new Bunifu.Framework.UI.BunifuDragControl(this.components);
            this.pnlHeadBar.SuspendLayout();
            this.bunifuPanel1.SuspendLayout();
            this.pnlLeft.SuspendLayout();
            this.pnlLeftImage.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pbLogo)).BeginInit();
            this.SuspendLayout();
            // 
            // pnlHeadBar
            // 
            this.pnlHeadBar.Controls.Add(this.pnlTopColorBar);
            this.pnlHeadBar.Controls.Add(this.lblYonetimBar);
            this.pnlHeadBar.Controls.Add(this.btnExit);
            this.pnlHeadBar.Dock = System.Windows.Forms.DockStyle.Top;
            this.pnlHeadBar.Location = new System.Drawing.Point(0, 0);
            this.pnlHeadBar.Name = "pnlHeadBar";
            this.pnlHeadBar.Size = new System.Drawing.Size(1280, 31);
            this.pnlHeadBar.TabIndex = 8;
            // 
            // lblYonetimBar
            // 
            this.lblYonetimBar.AllowParentOverrides = false;
            this.lblYonetimBar.AutoEllipsis = false;
            this.lblYonetimBar.AutoSize = false;
            this.lblYonetimBar.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblYonetimBar.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblYonetimBar.Enabled = false;
            this.lblYonetimBar.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblYonetimBar.Location = new System.Drawing.Point(3, 4);
            this.lblYonetimBar.Name = "lblYonetimBar";
            this.lblYonetimBar.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblYonetimBar.Size = new System.Drawing.Size(1221, 22);
            this.lblYonetimBar.TabIndex = 7;
            this.lblYonetimBar.Text = "--";
            this.lblYonetimBar.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.lblYonetimBar.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.pnlMain);
            this.bunifuPanel1.Controls.Add(this.pnlLastOrders);
            this.bunifuPanel1.Controls.Add(this.pnlLeft);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 31);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(1280, 737);
            this.bunifuPanel1.TabIndex = 9;
            // 
            // pnlMain
            // 
            this.pnlMain.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlMain.Location = new System.Drawing.Point(247, 110);
            this.pnlMain.Name = "pnlMain";
            this.pnlMain.Size = new System.Drawing.Size(1033, 627);
            this.pnlMain.TabIndex = 2;
            // 
            // pnlLastOrders
            // 
            this.pnlLastOrders.BackgroundColor = System.Drawing.Color.Transparent;
            this.pnlLastOrders.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pnlLastOrders.BackgroundImage")));
            this.pnlLastOrders.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pnlLastOrders.BorderColor = System.Drawing.Color.Transparent;
            this.pnlLastOrders.BorderRadius = 3;
            this.pnlLastOrders.BorderThickness = 1;
            this.pnlLastOrders.Dock = System.Windows.Forms.DockStyle.Top;
            this.pnlLastOrders.Location = new System.Drawing.Point(247, 0);
            this.pnlLastOrders.Name = "pnlLastOrders";
            this.pnlLastOrders.ShowBorders = true;
            this.pnlLastOrders.Size = new System.Drawing.Size(1033, 110);
            this.pnlLastOrders.TabIndex = 1;
            // 
            // pnlLeft
            // 
            this.pnlLeft.BackgroundColor = System.Drawing.Color.Transparent;
            this.pnlLeft.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pnlLeft.BackgroundImage")));
            this.pnlLeft.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pnlLeft.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(22)))), ((int)(((byte)(165)))));
            this.pnlLeft.BorderRadius = 0;
            this.pnlLeft.BorderThickness = 1;
            this.pnlLeft.Controls.Add(this.btnSepet);
            this.pnlLeft.Controls.Add(this.btnEtYemekleri);
            this.pnlLeft.Controls.Add(this.btnMakarnalar);
            this.pnlLeft.Controls.Add(this.btnCorbalar);
            this.pnlLeft.Controls.Add(this.btnSebzeYemekleri);
            this.pnlLeft.Controls.Add(this.btnIcecekler);
            this.pnlLeft.Controls.Add(this.btnSalatalar);
            this.pnlLeft.Controls.Add(this.btnTatlilar);
            this.pnlLeft.Controls.Add(this.pnlLeftImage);
            this.pnlLeft.Dock = System.Windows.Forms.DockStyle.Left;
            this.pnlLeft.Location = new System.Drawing.Point(0, 0);
            this.pnlLeft.Name = "pnlLeft";
            this.pnlLeft.ShowBorders = true;
            this.pnlLeft.Size = new System.Drawing.Size(247, 737);
            this.pnlLeft.TabIndex = 0;
            // 
            // btnSepet
            // 
            this.btnSepet.AllowAnimations = true;
            this.btnSepet.AllowMouseEffects = true;
            this.btnSepet.AllowToggling = false;
            this.btnSepet.AnimationSpeed = 200;
            this.btnSepet.AutoGenerateColors = false;
            this.btnSepet.AutoRoundBorders = false;
            this.btnSepet.AutoSizeLeftIcon = true;
            this.btnSepet.AutoSizeRightIcon = true;
            this.btnSepet.BackColor = System.Drawing.Color.Transparent;
            this.btnSepet.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(22)))), ((int)(((byte)(165)))));
            this.btnSepet.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSepet.BackgroundImage")));
            this.btnSepet.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSepet.ButtonText = "Sepet";
            this.btnSepet.ButtonTextMarginLeft = 0;
            this.btnSepet.ColorContrastOnClick = 45;
            this.btnSepet.ColorContrastOnHover = 45;
            this.btnSepet.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges19.BottomLeft = false;
            borderEdges19.BottomRight = true;
            borderEdges19.TopLeft = false;
            borderEdges19.TopRight = true;
            this.btnSepet.CustomizableEdges = borderEdges19;
            this.btnSepet.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSepet.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSepet.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSepet.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSepet.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnSepet.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSepet.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnSepet.ForeColor = System.Drawing.Color.White;
            this.btnSepet.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSepet.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSepet.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSepet.IconMarginLeft = 11;
            this.btnSepet.IconPadding = 10;
            this.btnSepet.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSepet.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSepet.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSepet.IconSize = 25;
            this.btnSepet.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(22)))), ((int)(((byte)(165)))));
            this.btnSepet.IdleBorderRadius = 1;
            this.btnSepet.IdleBorderThickness = 1;
            this.btnSepet.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(22)))), ((int)(((byte)(165)))));
            this.btnSepet.IdleIconLeftImage = null;
            this.btnSepet.IdleIconRightImage = null;
            this.btnSepet.IndicateFocus = false;
            this.btnSepet.Location = new System.Drawing.Point(0, 665);
            this.btnSepet.Name = "btnSepet";
            this.btnSepet.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSepet.OnDisabledState.BorderRadius = 1;
            this.btnSepet.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSepet.OnDisabledState.BorderThickness = 1;
            this.btnSepet.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSepet.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSepet.OnDisabledState.IconLeftImage = null;
            this.btnSepet.OnDisabledState.IconRightImage = null;
            this.btnSepet.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnSepet.onHoverState.BorderRadius = 1;
            this.btnSepet.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSepet.onHoverState.BorderThickness = 1;
            this.btnSepet.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnSepet.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSepet.onHoverState.IconLeftImage = null;
            this.btnSepet.onHoverState.IconRightImage = null;
            this.btnSepet.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(22)))), ((int)(((byte)(165)))));
            this.btnSepet.OnIdleState.BorderRadius = 1;
            this.btnSepet.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSepet.OnIdleState.BorderThickness = 1;
            this.btnSepet.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(22)))), ((int)(((byte)(165)))));
            this.btnSepet.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSepet.OnIdleState.IconLeftImage = null;
            this.btnSepet.OnIdleState.IconRightImage = null;
            this.btnSepet.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSepet.OnPressedState.BorderRadius = 1;
            this.btnSepet.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSepet.OnPressedState.BorderThickness = 1;
            this.btnSepet.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSepet.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSepet.OnPressedState.IconLeftImage = null;
            this.btnSepet.OnPressedState.IconRightImage = null;
            this.btnSepet.Size = new System.Drawing.Size(247, 72);
            this.btnSepet.TabIndex = 15;
            this.btnSepet.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSepet.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSepet.TextMarginLeft = 0;
            this.btnSepet.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSepet.UseDefaultRadiusAndThickness = true;
            this.btnSepet.Click += new System.EventHandler(this.btnSepet_Click);
            // 
            // btnEtYemekleri
            // 
            this.btnEtYemekleri.AllowAnimations = true;
            this.btnEtYemekleri.AllowMouseEffects = true;
            this.btnEtYemekleri.AllowToggling = false;
            this.btnEtYemekleri.AnimationSpeed = 200;
            this.btnEtYemekleri.AutoGenerateColors = false;
            this.btnEtYemekleri.AutoRoundBorders = false;
            this.btnEtYemekleri.AutoSizeLeftIcon = true;
            this.btnEtYemekleri.AutoSizeRightIcon = true;
            this.btnEtYemekleri.BackColor = System.Drawing.Color.Transparent;
            this.btnEtYemekleri.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(22)))), ((int)(((byte)(165)))));
            this.btnEtYemekleri.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnEtYemekleri.BackgroundImage")));
            this.btnEtYemekleri.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEtYemekleri.ButtonText = "Et Yemekleri";
            this.btnEtYemekleri.ButtonTextMarginLeft = 0;
            this.btnEtYemekleri.ColorContrastOnClick = 45;
            this.btnEtYemekleri.ColorContrastOnHover = 45;
            this.btnEtYemekleri.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges20.BottomLeft = false;
            borderEdges20.BottomRight = true;
            borderEdges20.TopLeft = false;
            borderEdges20.TopRight = true;
            this.btnEtYemekleri.CustomizableEdges = borderEdges20;
            this.btnEtYemekleri.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnEtYemekleri.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEtYemekleri.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEtYemekleri.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEtYemekleri.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnEtYemekleri.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnEtYemekleri.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnEtYemekleri.ForeColor = System.Drawing.Color.White;
            this.btnEtYemekleri.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnEtYemekleri.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnEtYemekleri.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnEtYemekleri.IconMarginLeft = 11;
            this.btnEtYemekleri.IconPadding = 10;
            this.btnEtYemekleri.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnEtYemekleri.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnEtYemekleri.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnEtYemekleri.IconSize = 25;
            this.btnEtYemekleri.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(22)))), ((int)(((byte)(165)))));
            this.btnEtYemekleri.IdleBorderRadius = 1;
            this.btnEtYemekleri.IdleBorderThickness = 1;
            this.btnEtYemekleri.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(22)))), ((int)(((byte)(165)))));
            this.btnEtYemekleri.IdleIconLeftImage = null;
            this.btnEtYemekleri.IdleIconRightImage = null;
            this.btnEtYemekleri.IndicateFocus = false;
            this.btnEtYemekleri.Location = new System.Drawing.Point(0, 600);
            this.btnEtYemekleri.Name = "btnEtYemekleri";
            this.btnEtYemekleri.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEtYemekleri.OnDisabledState.BorderRadius = 1;
            this.btnEtYemekleri.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEtYemekleri.OnDisabledState.BorderThickness = 1;
            this.btnEtYemekleri.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEtYemekleri.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEtYemekleri.OnDisabledState.IconLeftImage = null;
            this.btnEtYemekleri.OnDisabledState.IconRightImage = null;
            this.btnEtYemekleri.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnEtYemekleri.onHoverState.BorderRadius = 1;
            this.btnEtYemekleri.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEtYemekleri.onHoverState.BorderThickness = 1;
            this.btnEtYemekleri.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnEtYemekleri.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnEtYemekleri.onHoverState.IconLeftImage = null;
            this.btnEtYemekleri.onHoverState.IconRightImage = null;
            this.btnEtYemekleri.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(22)))), ((int)(((byte)(165)))));
            this.btnEtYemekleri.OnIdleState.BorderRadius = 1;
            this.btnEtYemekleri.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEtYemekleri.OnIdleState.BorderThickness = 1;
            this.btnEtYemekleri.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(22)))), ((int)(((byte)(165)))));
            this.btnEtYemekleri.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnEtYemekleri.OnIdleState.IconLeftImage = null;
            this.btnEtYemekleri.OnIdleState.IconRightImage = null;
            this.btnEtYemekleri.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEtYemekleri.OnPressedState.BorderRadius = 1;
            this.btnEtYemekleri.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEtYemekleri.OnPressedState.BorderThickness = 1;
            this.btnEtYemekleri.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEtYemekleri.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnEtYemekleri.OnPressedState.IconLeftImage = null;
            this.btnEtYemekleri.OnPressedState.IconRightImage = null;
            this.btnEtYemekleri.Size = new System.Drawing.Size(247, 65);
            this.btnEtYemekleri.TabIndex = 14;
            this.btnEtYemekleri.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnEtYemekleri.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnEtYemekleri.TextMarginLeft = 0;
            this.btnEtYemekleri.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnEtYemekleri.UseDefaultRadiusAndThickness = true;
            this.btnEtYemekleri.Click += new System.EventHandler(this.MenuButonlari);
            // 
            // btnMakarnalar
            // 
            this.btnMakarnalar.AllowAnimations = true;
            this.btnMakarnalar.AllowMouseEffects = true;
            this.btnMakarnalar.AllowToggling = false;
            this.btnMakarnalar.AnimationSpeed = 200;
            this.btnMakarnalar.AutoGenerateColors = false;
            this.btnMakarnalar.AutoRoundBorders = false;
            this.btnMakarnalar.AutoSizeLeftIcon = true;
            this.btnMakarnalar.AutoSizeRightIcon = true;
            this.btnMakarnalar.BackColor = System.Drawing.Color.Transparent;
            this.btnMakarnalar.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(22)))), ((int)(((byte)(165)))));
            this.btnMakarnalar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnMakarnalar.BackgroundImage")));
            this.btnMakarnalar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnMakarnalar.ButtonText = "Makarnalar";
            this.btnMakarnalar.ButtonTextMarginLeft = 0;
            this.btnMakarnalar.ColorContrastOnClick = 45;
            this.btnMakarnalar.ColorContrastOnHover = 45;
            this.btnMakarnalar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges21.BottomLeft = false;
            borderEdges21.BottomRight = true;
            borderEdges21.TopLeft = false;
            borderEdges21.TopRight = true;
            this.btnMakarnalar.CustomizableEdges = borderEdges21;
            this.btnMakarnalar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnMakarnalar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnMakarnalar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnMakarnalar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnMakarnalar.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnMakarnalar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnMakarnalar.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnMakarnalar.ForeColor = System.Drawing.Color.White;
            this.btnMakarnalar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnMakarnalar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnMakarnalar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnMakarnalar.IconMarginLeft = 11;
            this.btnMakarnalar.IconPadding = 10;
            this.btnMakarnalar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnMakarnalar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnMakarnalar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnMakarnalar.IconSize = 25;
            this.btnMakarnalar.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(22)))), ((int)(((byte)(165)))));
            this.btnMakarnalar.IdleBorderRadius = 1;
            this.btnMakarnalar.IdleBorderThickness = 1;
            this.btnMakarnalar.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(22)))), ((int)(((byte)(165)))));
            this.btnMakarnalar.IdleIconLeftImage = null;
            this.btnMakarnalar.IdleIconRightImage = null;
            this.btnMakarnalar.IndicateFocus = false;
            this.btnMakarnalar.Location = new System.Drawing.Point(0, 535);
            this.btnMakarnalar.Name = "btnMakarnalar";
            this.btnMakarnalar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnMakarnalar.OnDisabledState.BorderRadius = 1;
            this.btnMakarnalar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnMakarnalar.OnDisabledState.BorderThickness = 1;
            this.btnMakarnalar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnMakarnalar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnMakarnalar.OnDisabledState.IconLeftImage = null;
            this.btnMakarnalar.OnDisabledState.IconRightImage = null;
            this.btnMakarnalar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnMakarnalar.onHoverState.BorderRadius = 1;
            this.btnMakarnalar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnMakarnalar.onHoverState.BorderThickness = 1;
            this.btnMakarnalar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnMakarnalar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnMakarnalar.onHoverState.IconLeftImage = null;
            this.btnMakarnalar.onHoverState.IconRightImage = null;
            this.btnMakarnalar.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(22)))), ((int)(((byte)(165)))));
            this.btnMakarnalar.OnIdleState.BorderRadius = 1;
            this.btnMakarnalar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnMakarnalar.OnIdleState.BorderThickness = 1;
            this.btnMakarnalar.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(22)))), ((int)(((byte)(165)))));
            this.btnMakarnalar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnMakarnalar.OnIdleState.IconLeftImage = null;
            this.btnMakarnalar.OnIdleState.IconRightImage = null;
            this.btnMakarnalar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnMakarnalar.OnPressedState.BorderRadius = 1;
            this.btnMakarnalar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnMakarnalar.OnPressedState.BorderThickness = 1;
            this.btnMakarnalar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnMakarnalar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnMakarnalar.OnPressedState.IconLeftImage = null;
            this.btnMakarnalar.OnPressedState.IconRightImage = null;
            this.btnMakarnalar.Size = new System.Drawing.Size(247, 65);
            this.btnMakarnalar.TabIndex = 13;
            this.btnMakarnalar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnMakarnalar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnMakarnalar.TextMarginLeft = 0;
            this.btnMakarnalar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnMakarnalar.UseDefaultRadiusAndThickness = true;
            this.btnMakarnalar.Click += new System.EventHandler(this.MenuButonlari);
            // 
            // btnCorbalar
            // 
            this.btnCorbalar.AllowAnimations = true;
            this.btnCorbalar.AllowMouseEffects = true;
            this.btnCorbalar.AllowToggling = false;
            this.btnCorbalar.AnimationSpeed = 200;
            this.btnCorbalar.AutoGenerateColors = false;
            this.btnCorbalar.AutoRoundBorders = false;
            this.btnCorbalar.AutoSizeLeftIcon = true;
            this.btnCorbalar.AutoSizeRightIcon = true;
            this.btnCorbalar.BackColor = System.Drawing.Color.Transparent;
            this.btnCorbalar.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(22)))), ((int)(((byte)(165)))));
            this.btnCorbalar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCorbalar.BackgroundImage")));
            this.btnCorbalar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCorbalar.ButtonText = "Çorbalar";
            this.btnCorbalar.ButtonTextMarginLeft = 0;
            this.btnCorbalar.ColorContrastOnClick = 45;
            this.btnCorbalar.ColorContrastOnHover = 45;
            this.btnCorbalar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges22.BottomLeft = false;
            borderEdges22.BottomRight = true;
            borderEdges22.TopLeft = false;
            borderEdges22.TopRight = true;
            this.btnCorbalar.CustomizableEdges = borderEdges22;
            this.btnCorbalar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCorbalar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCorbalar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCorbalar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCorbalar.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnCorbalar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCorbalar.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnCorbalar.ForeColor = System.Drawing.Color.White;
            this.btnCorbalar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCorbalar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCorbalar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCorbalar.IconMarginLeft = 11;
            this.btnCorbalar.IconPadding = 10;
            this.btnCorbalar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCorbalar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCorbalar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCorbalar.IconSize = 25;
            this.btnCorbalar.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(22)))), ((int)(((byte)(165)))));
            this.btnCorbalar.IdleBorderRadius = 1;
            this.btnCorbalar.IdleBorderThickness = 1;
            this.btnCorbalar.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(22)))), ((int)(((byte)(165)))));
            this.btnCorbalar.IdleIconLeftImage = null;
            this.btnCorbalar.IdleIconRightImage = null;
            this.btnCorbalar.IndicateFocus = false;
            this.btnCorbalar.Location = new System.Drawing.Point(0, 470);
            this.btnCorbalar.Name = "btnCorbalar";
            this.btnCorbalar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCorbalar.OnDisabledState.BorderRadius = 1;
            this.btnCorbalar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCorbalar.OnDisabledState.BorderThickness = 1;
            this.btnCorbalar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCorbalar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCorbalar.OnDisabledState.IconLeftImage = null;
            this.btnCorbalar.OnDisabledState.IconRightImage = null;
            this.btnCorbalar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnCorbalar.onHoverState.BorderRadius = 1;
            this.btnCorbalar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCorbalar.onHoverState.BorderThickness = 1;
            this.btnCorbalar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnCorbalar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnCorbalar.onHoverState.IconLeftImage = null;
            this.btnCorbalar.onHoverState.IconRightImage = null;
            this.btnCorbalar.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(22)))), ((int)(((byte)(165)))));
            this.btnCorbalar.OnIdleState.BorderRadius = 1;
            this.btnCorbalar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCorbalar.OnIdleState.BorderThickness = 1;
            this.btnCorbalar.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(22)))), ((int)(((byte)(165)))));
            this.btnCorbalar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnCorbalar.OnIdleState.IconLeftImage = null;
            this.btnCorbalar.OnIdleState.IconRightImage = null;
            this.btnCorbalar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCorbalar.OnPressedState.BorderRadius = 1;
            this.btnCorbalar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCorbalar.OnPressedState.BorderThickness = 1;
            this.btnCorbalar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCorbalar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCorbalar.OnPressedState.IconLeftImage = null;
            this.btnCorbalar.OnPressedState.IconRightImage = null;
            this.btnCorbalar.Size = new System.Drawing.Size(247, 65);
            this.btnCorbalar.TabIndex = 12;
            this.btnCorbalar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCorbalar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCorbalar.TextMarginLeft = 0;
            this.btnCorbalar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCorbalar.UseDefaultRadiusAndThickness = true;
            this.btnCorbalar.Click += new System.EventHandler(this.MenuButonlari);
            // 
            // btnSebzeYemekleri
            // 
            this.btnSebzeYemekleri.AllowAnimations = true;
            this.btnSebzeYemekleri.AllowMouseEffects = true;
            this.btnSebzeYemekleri.AllowToggling = false;
            this.btnSebzeYemekleri.AnimationSpeed = 200;
            this.btnSebzeYemekleri.AutoGenerateColors = false;
            this.btnSebzeYemekleri.AutoRoundBorders = false;
            this.btnSebzeYemekleri.AutoSizeLeftIcon = true;
            this.btnSebzeYemekleri.AutoSizeRightIcon = true;
            this.btnSebzeYemekleri.BackColor = System.Drawing.Color.Transparent;
            this.btnSebzeYemekleri.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(22)))), ((int)(((byte)(165)))));
            this.btnSebzeYemekleri.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSebzeYemekleri.BackgroundImage")));
            this.btnSebzeYemekleri.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSebzeYemekleri.ButtonText = "Sebze Yemekleri";
            this.btnSebzeYemekleri.ButtonTextMarginLeft = 0;
            this.btnSebzeYemekleri.ColorContrastOnClick = 45;
            this.btnSebzeYemekleri.ColorContrastOnHover = 45;
            this.btnSebzeYemekleri.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges23.BottomLeft = false;
            borderEdges23.BottomRight = true;
            borderEdges23.TopLeft = false;
            borderEdges23.TopRight = true;
            this.btnSebzeYemekleri.CustomizableEdges = borderEdges23;
            this.btnSebzeYemekleri.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSebzeYemekleri.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSebzeYemekleri.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSebzeYemekleri.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSebzeYemekleri.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnSebzeYemekleri.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSebzeYemekleri.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnSebzeYemekleri.ForeColor = System.Drawing.Color.White;
            this.btnSebzeYemekleri.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSebzeYemekleri.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSebzeYemekleri.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSebzeYemekleri.IconMarginLeft = 11;
            this.btnSebzeYemekleri.IconPadding = 10;
            this.btnSebzeYemekleri.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSebzeYemekleri.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSebzeYemekleri.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSebzeYemekleri.IconSize = 25;
            this.btnSebzeYemekleri.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(22)))), ((int)(((byte)(165)))));
            this.btnSebzeYemekleri.IdleBorderRadius = 1;
            this.btnSebzeYemekleri.IdleBorderThickness = 1;
            this.btnSebzeYemekleri.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(22)))), ((int)(((byte)(165)))));
            this.btnSebzeYemekleri.IdleIconLeftImage = null;
            this.btnSebzeYemekleri.IdleIconRightImage = null;
            this.btnSebzeYemekleri.IndicateFocus = false;
            this.btnSebzeYemekleri.Location = new System.Drawing.Point(0, 405);
            this.btnSebzeYemekleri.Name = "btnSebzeYemekleri";
            this.btnSebzeYemekleri.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSebzeYemekleri.OnDisabledState.BorderRadius = 1;
            this.btnSebzeYemekleri.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSebzeYemekleri.OnDisabledState.BorderThickness = 1;
            this.btnSebzeYemekleri.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSebzeYemekleri.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSebzeYemekleri.OnDisabledState.IconLeftImage = null;
            this.btnSebzeYemekleri.OnDisabledState.IconRightImage = null;
            this.btnSebzeYemekleri.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnSebzeYemekleri.onHoverState.BorderRadius = 1;
            this.btnSebzeYemekleri.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSebzeYemekleri.onHoverState.BorderThickness = 1;
            this.btnSebzeYemekleri.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnSebzeYemekleri.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSebzeYemekleri.onHoverState.IconLeftImage = null;
            this.btnSebzeYemekleri.onHoverState.IconRightImage = null;
            this.btnSebzeYemekleri.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(22)))), ((int)(((byte)(165)))));
            this.btnSebzeYemekleri.OnIdleState.BorderRadius = 1;
            this.btnSebzeYemekleri.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSebzeYemekleri.OnIdleState.BorderThickness = 1;
            this.btnSebzeYemekleri.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(22)))), ((int)(((byte)(165)))));
            this.btnSebzeYemekleri.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSebzeYemekleri.OnIdleState.IconLeftImage = null;
            this.btnSebzeYemekleri.OnIdleState.IconRightImage = null;
            this.btnSebzeYemekleri.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSebzeYemekleri.OnPressedState.BorderRadius = 1;
            this.btnSebzeYemekleri.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSebzeYemekleri.OnPressedState.BorderThickness = 1;
            this.btnSebzeYemekleri.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSebzeYemekleri.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSebzeYemekleri.OnPressedState.IconLeftImage = null;
            this.btnSebzeYemekleri.OnPressedState.IconRightImage = null;
            this.btnSebzeYemekleri.Size = new System.Drawing.Size(247, 65);
            this.btnSebzeYemekleri.TabIndex = 11;
            this.btnSebzeYemekleri.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSebzeYemekleri.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSebzeYemekleri.TextMarginLeft = 0;
            this.btnSebzeYemekleri.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSebzeYemekleri.UseDefaultRadiusAndThickness = true;
            this.btnSebzeYemekleri.Click += new System.EventHandler(this.MenuButonlari);
            // 
            // btnIcecekler
            // 
            this.btnIcecekler.AllowAnimations = true;
            this.btnIcecekler.AllowMouseEffects = true;
            this.btnIcecekler.AllowToggling = false;
            this.btnIcecekler.AnimationSpeed = 200;
            this.btnIcecekler.AutoGenerateColors = false;
            this.btnIcecekler.AutoRoundBorders = false;
            this.btnIcecekler.AutoSizeLeftIcon = true;
            this.btnIcecekler.AutoSizeRightIcon = true;
            this.btnIcecekler.BackColor = System.Drawing.Color.Transparent;
            this.btnIcecekler.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(22)))), ((int)(((byte)(165)))));
            this.btnIcecekler.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnIcecekler.BackgroundImage")));
            this.btnIcecekler.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnIcecekler.ButtonText = "İçecekler";
            this.btnIcecekler.ButtonTextMarginLeft = 0;
            this.btnIcecekler.ColorContrastOnClick = 45;
            this.btnIcecekler.ColorContrastOnHover = 45;
            this.btnIcecekler.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges24.BottomLeft = false;
            borderEdges24.BottomRight = true;
            borderEdges24.TopLeft = false;
            borderEdges24.TopRight = true;
            this.btnIcecekler.CustomizableEdges = borderEdges24;
            this.btnIcecekler.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnIcecekler.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnIcecekler.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnIcecekler.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnIcecekler.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnIcecekler.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnIcecekler.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnIcecekler.ForeColor = System.Drawing.Color.White;
            this.btnIcecekler.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnIcecekler.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnIcecekler.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnIcecekler.IconMarginLeft = 11;
            this.btnIcecekler.IconPadding = 10;
            this.btnIcecekler.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnIcecekler.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnIcecekler.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnIcecekler.IconSize = 25;
            this.btnIcecekler.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(22)))), ((int)(((byte)(165)))));
            this.btnIcecekler.IdleBorderRadius = 1;
            this.btnIcecekler.IdleBorderThickness = 1;
            this.btnIcecekler.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(22)))), ((int)(((byte)(165)))));
            this.btnIcecekler.IdleIconLeftImage = null;
            this.btnIcecekler.IdleIconRightImage = null;
            this.btnIcecekler.IndicateFocus = false;
            this.btnIcecekler.Location = new System.Drawing.Point(0, 340);
            this.btnIcecekler.Name = "btnIcecekler";
            this.btnIcecekler.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnIcecekler.OnDisabledState.BorderRadius = 1;
            this.btnIcecekler.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnIcecekler.OnDisabledState.BorderThickness = 1;
            this.btnIcecekler.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnIcecekler.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnIcecekler.OnDisabledState.IconLeftImage = null;
            this.btnIcecekler.OnDisabledState.IconRightImage = null;
            this.btnIcecekler.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnIcecekler.onHoverState.BorderRadius = 1;
            this.btnIcecekler.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnIcecekler.onHoverState.BorderThickness = 1;
            this.btnIcecekler.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnIcecekler.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnIcecekler.onHoverState.IconLeftImage = null;
            this.btnIcecekler.onHoverState.IconRightImage = null;
            this.btnIcecekler.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(22)))), ((int)(((byte)(165)))));
            this.btnIcecekler.OnIdleState.BorderRadius = 1;
            this.btnIcecekler.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnIcecekler.OnIdleState.BorderThickness = 1;
            this.btnIcecekler.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(22)))), ((int)(((byte)(165)))));
            this.btnIcecekler.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnIcecekler.OnIdleState.IconLeftImage = null;
            this.btnIcecekler.OnIdleState.IconRightImage = null;
            this.btnIcecekler.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnIcecekler.OnPressedState.BorderRadius = 1;
            this.btnIcecekler.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnIcecekler.OnPressedState.BorderThickness = 1;
            this.btnIcecekler.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnIcecekler.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnIcecekler.OnPressedState.IconLeftImage = null;
            this.btnIcecekler.OnPressedState.IconRightImage = null;
            this.btnIcecekler.Size = new System.Drawing.Size(247, 65);
            this.btnIcecekler.TabIndex = 10;
            this.btnIcecekler.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnIcecekler.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnIcecekler.TextMarginLeft = 0;
            this.btnIcecekler.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnIcecekler.UseDefaultRadiusAndThickness = true;
            this.btnIcecekler.Click += new System.EventHandler(this.MenuButonlari);
            // 
            // btnSalatalar
            // 
            this.btnSalatalar.AllowAnimations = true;
            this.btnSalatalar.AllowMouseEffects = true;
            this.btnSalatalar.AllowToggling = false;
            this.btnSalatalar.AnimationSpeed = 200;
            this.btnSalatalar.AutoGenerateColors = false;
            this.btnSalatalar.AutoRoundBorders = false;
            this.btnSalatalar.AutoSizeLeftIcon = true;
            this.btnSalatalar.AutoSizeRightIcon = true;
            this.btnSalatalar.BackColor = System.Drawing.Color.Transparent;
            this.btnSalatalar.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(22)))), ((int)(((byte)(165)))));
            this.btnSalatalar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSalatalar.BackgroundImage")));
            this.btnSalatalar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSalatalar.ButtonText = "Salatalar";
            this.btnSalatalar.ButtonTextMarginLeft = 0;
            this.btnSalatalar.ColorContrastOnClick = 45;
            this.btnSalatalar.ColorContrastOnHover = 45;
            this.btnSalatalar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges25.BottomLeft = false;
            borderEdges25.BottomRight = true;
            borderEdges25.TopLeft = false;
            borderEdges25.TopRight = true;
            this.btnSalatalar.CustomizableEdges = borderEdges25;
            this.btnSalatalar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSalatalar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSalatalar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSalatalar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSalatalar.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnSalatalar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSalatalar.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnSalatalar.ForeColor = System.Drawing.Color.White;
            this.btnSalatalar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSalatalar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSalatalar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSalatalar.IconMarginLeft = 11;
            this.btnSalatalar.IconPadding = 10;
            this.btnSalatalar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSalatalar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSalatalar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSalatalar.IconSize = 25;
            this.btnSalatalar.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(22)))), ((int)(((byte)(165)))));
            this.btnSalatalar.IdleBorderRadius = 1;
            this.btnSalatalar.IdleBorderThickness = 1;
            this.btnSalatalar.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(22)))), ((int)(((byte)(165)))));
            this.btnSalatalar.IdleIconLeftImage = null;
            this.btnSalatalar.IdleIconRightImage = null;
            this.btnSalatalar.IndicateFocus = false;
            this.btnSalatalar.Location = new System.Drawing.Point(0, 275);
            this.btnSalatalar.Name = "btnSalatalar";
            this.btnSalatalar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSalatalar.OnDisabledState.BorderRadius = 1;
            this.btnSalatalar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSalatalar.OnDisabledState.BorderThickness = 1;
            this.btnSalatalar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSalatalar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSalatalar.OnDisabledState.IconLeftImage = null;
            this.btnSalatalar.OnDisabledState.IconRightImage = null;
            this.btnSalatalar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnSalatalar.onHoverState.BorderRadius = 1;
            this.btnSalatalar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSalatalar.onHoverState.BorderThickness = 1;
            this.btnSalatalar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnSalatalar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSalatalar.onHoverState.IconLeftImage = null;
            this.btnSalatalar.onHoverState.IconRightImage = null;
            this.btnSalatalar.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(22)))), ((int)(((byte)(165)))));
            this.btnSalatalar.OnIdleState.BorderRadius = 1;
            this.btnSalatalar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSalatalar.OnIdleState.BorderThickness = 1;
            this.btnSalatalar.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(22)))), ((int)(((byte)(165)))));
            this.btnSalatalar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSalatalar.OnIdleState.IconLeftImage = null;
            this.btnSalatalar.OnIdleState.IconRightImage = null;
            this.btnSalatalar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSalatalar.OnPressedState.BorderRadius = 1;
            this.btnSalatalar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSalatalar.OnPressedState.BorderThickness = 1;
            this.btnSalatalar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSalatalar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSalatalar.OnPressedState.IconLeftImage = null;
            this.btnSalatalar.OnPressedState.IconRightImage = null;
            this.btnSalatalar.Size = new System.Drawing.Size(247, 65);
            this.btnSalatalar.TabIndex = 9;
            this.btnSalatalar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSalatalar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSalatalar.TextMarginLeft = 0;
            this.btnSalatalar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSalatalar.UseDefaultRadiusAndThickness = true;
            this.btnSalatalar.Click += new System.EventHandler(this.MenuButonlari);
            // 
            // btnTatlilar
            // 
            this.btnTatlilar.AllowAnimations = true;
            this.btnTatlilar.AllowMouseEffects = true;
            this.btnTatlilar.AllowToggling = false;
            this.btnTatlilar.AnimationSpeed = 200;
            this.btnTatlilar.AutoGenerateColors = false;
            this.btnTatlilar.AutoRoundBorders = false;
            this.btnTatlilar.AutoSizeLeftIcon = true;
            this.btnTatlilar.AutoSizeRightIcon = true;
            this.btnTatlilar.BackColor = System.Drawing.Color.Transparent;
            this.btnTatlilar.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(22)))), ((int)(((byte)(165)))));
            this.btnTatlilar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnTatlilar.BackgroundImage")));
            this.btnTatlilar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTatlilar.ButtonText = "Tatlılar";
            this.btnTatlilar.ButtonTextMarginLeft = 0;
            this.btnTatlilar.ColorContrastOnClick = 45;
            this.btnTatlilar.ColorContrastOnHover = 45;
            this.btnTatlilar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges26.BottomLeft = false;
            borderEdges26.BottomRight = true;
            borderEdges26.TopLeft = false;
            borderEdges26.TopRight = true;
            this.btnTatlilar.CustomizableEdges = borderEdges26;
            this.btnTatlilar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnTatlilar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(162)))), ((int)(((byte)(162)))));
            this.btnTatlilar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(162)))), ((int)(((byte)(162)))));
            this.btnTatlilar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnTatlilar.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnTatlilar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnTatlilar.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnTatlilar.ForeColor = System.Drawing.Color.White;
            this.btnTatlilar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnTatlilar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnTatlilar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnTatlilar.IconMarginLeft = 11;
            this.btnTatlilar.IconPadding = 10;
            this.btnTatlilar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnTatlilar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnTatlilar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnTatlilar.IconSize = 25;
            this.btnTatlilar.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(22)))), ((int)(((byte)(165)))));
            this.btnTatlilar.IdleBorderRadius = 1;
            this.btnTatlilar.IdleBorderThickness = 1;
            this.btnTatlilar.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(22)))), ((int)(((byte)(165)))));
            this.btnTatlilar.IdleIconLeftImage = null;
            this.btnTatlilar.IdleIconRightImage = null;
            this.btnTatlilar.IndicateFocus = false;
            this.btnTatlilar.Location = new System.Drawing.Point(0, 210);
            this.btnTatlilar.Name = "btnTatlilar";
            this.btnTatlilar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(162)))), ((int)(((byte)(162)))));
            this.btnTatlilar.OnDisabledState.BorderRadius = 1;
            this.btnTatlilar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTatlilar.OnDisabledState.BorderThickness = 1;
            this.btnTatlilar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(162)))), ((int)(((byte)(162)))));
            this.btnTatlilar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnTatlilar.OnDisabledState.IconLeftImage = null;
            this.btnTatlilar.OnDisabledState.IconRightImage = null;
            this.btnTatlilar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnTatlilar.onHoverState.BorderRadius = 1;
            this.btnTatlilar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTatlilar.onHoverState.BorderThickness = 1;
            this.btnTatlilar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnTatlilar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnTatlilar.onHoverState.IconLeftImage = null;
            this.btnTatlilar.onHoverState.IconRightImage = null;
            this.btnTatlilar.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(22)))), ((int)(((byte)(165)))));
            this.btnTatlilar.OnIdleState.BorderRadius = 1;
            this.btnTatlilar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTatlilar.OnIdleState.BorderThickness = 1;
            this.btnTatlilar.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(22)))), ((int)(((byte)(165)))));
            this.btnTatlilar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnTatlilar.OnIdleState.IconLeftImage = null;
            this.btnTatlilar.OnIdleState.IconRightImage = null;
            this.btnTatlilar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnTatlilar.OnPressedState.BorderRadius = 1;
            this.btnTatlilar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTatlilar.OnPressedState.BorderThickness = 1;
            this.btnTatlilar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnTatlilar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnTatlilar.OnPressedState.IconLeftImage = null;
            this.btnTatlilar.OnPressedState.IconRightImage = null;
            this.btnTatlilar.Size = new System.Drawing.Size(247, 65);
            this.btnTatlilar.TabIndex = 8;
            this.btnTatlilar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnTatlilar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnTatlilar.TextMarginLeft = 0;
            this.btnTatlilar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnTatlilar.UseDefaultRadiusAndThickness = true;
            this.btnTatlilar.Click += new System.EventHandler(this.MenuButonlari);
            // 
            // pnlLeftImage
            // 
            this.pnlLeftImage.BackgroundColor = System.Drawing.Color.Transparent;
            this.pnlLeftImage.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pnlLeftImage.BackgroundImage")));
            this.pnlLeftImage.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pnlLeftImage.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(22)))), ((int)(((byte)(165)))));
            this.pnlLeftImage.BorderRadius = 0;
            this.pnlLeftImage.BorderThickness = 1;
            this.pnlLeftImage.Controls.Add(this.pbLogo);
            this.pnlLeftImage.Dock = System.Windows.Forms.DockStyle.Top;
            this.pnlLeftImage.Location = new System.Drawing.Point(0, 0);
            this.pnlLeftImage.Name = "pnlLeftImage";
            this.pnlLeftImage.ShowBorders = true;
            this.pnlLeftImage.Size = new System.Drawing.Size(247, 210);
            this.pnlLeftImage.TabIndex = 0;
            // 
            // pbLogo
            // 
            this.pbLogo.AllowFocused = false;
            this.pbLogo.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.pbLogo.AutoSizeHeight = true;
            this.pbLogo.BorderRadius = 78;
            this.pbLogo.Image = ((System.Drawing.Image)(resources.GetObject("pbLogo.Image")));
            this.pbLogo.IsCircle = true;
            this.pbLogo.Location = new System.Drawing.Point(45, 27);
            this.pbLogo.Name = "pbLogo";
            this.pbLogo.Size = new System.Drawing.Size(157, 157);
            this.pbLogo.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pbLogo.TabIndex = 0;
            this.pbLogo.TabStop = false;
            this.pbLogo.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // pnlTopColorBar
            // 
            this.pnlTopColorBar.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(22)))), ((int)(((byte)(165)))));
            this.pnlTopColorBar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pnlTopColorBar.BackgroundImage")));
            this.pnlTopColorBar.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pnlTopColorBar.BorderColor = System.Drawing.Color.Transparent;
            this.pnlTopColorBar.BorderRadius = 3;
            this.pnlTopColorBar.BorderThickness = 1;
            this.pnlTopColorBar.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.pnlTopColorBar.Location = new System.Drawing.Point(0, 30);
            this.pnlTopColorBar.Name = "pnlTopColorBar";
            this.pnlTopColorBar.ShowBorders = true;
            this.pnlTopColorBar.Size = new System.Drawing.Size(1280, 1);
            this.pnlTopColorBar.TabIndex = 8;
            // 
            // btnExit
            // 
            this.btnExit.AllowAnimations = true;
            this.btnExit.AllowMouseEffects = true;
            this.btnExit.AllowToggling = false;
            this.btnExit.AnimationSpeed = 200;
            this.btnExit.AutoGenerateColors = false;
            this.btnExit.AutoRoundBorders = false;
            this.btnExit.AutoSizeLeftIcon = true;
            this.btnExit.AutoSizeRightIcon = true;
            this.btnExit.BackColor = System.Drawing.Color.Transparent;
            this.btnExit.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(15)))), ((int)(((byte)(15)))));
            this.btnExit.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnExit.BackgroundImage")));
            this.btnExit.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExit.ButtonText = "X";
            this.btnExit.ButtonTextMarginLeft = 0;
            this.btnExit.ColorContrastOnClick = 45;
            this.btnExit.ColorContrastOnHover = 45;
            this.btnExit.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges27.BottomLeft = true;
            borderEdges27.BottomRight = true;
            borderEdges27.TopLeft = true;
            borderEdges27.TopRight = true;
            this.btnExit.CustomizableEdges = borderEdges27;
            this.btnExit.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnExit.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnExit.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnExit.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnExit.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnExit.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.btnExit.ForeColor = System.Drawing.Color.White;
            this.btnExit.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnExit.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnExit.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnExit.IconMarginLeft = 11;
            this.btnExit.IconPadding = 10;
            this.btnExit.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnExit.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnExit.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnExit.IconSize = 25;
            this.btnExit.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(15)))), ((int)(((byte)(15)))));
            this.btnExit.IdleBorderRadius = 1;
            this.btnExit.IdleBorderThickness = 1;
            this.btnExit.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(15)))), ((int)(((byte)(15)))));
            this.btnExit.IdleIconLeftImage = null;
            this.btnExit.IdleIconRightImage = null;
            this.btnExit.IndicateFocus = false;
            this.btnExit.Location = new System.Drawing.Point(1230, 0);
            this.btnExit.Name = "btnExit";
            this.btnExit.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnExit.OnDisabledState.BorderRadius = 1;
            this.btnExit.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExit.OnDisabledState.BorderThickness = 1;
            this.btnExit.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnExit.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnExit.OnDisabledState.IconLeftImage = null;
            this.btnExit.OnDisabledState.IconRightImage = null;
            this.btnExit.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(32)))), ((int)(((byte)(32)))));
            this.btnExit.onHoverState.BorderRadius = 1;
            this.btnExit.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExit.onHoverState.BorderThickness = 1;
            this.btnExit.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(32)))), ((int)(((byte)(32)))));
            this.btnExit.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnExit.onHoverState.IconLeftImage = null;
            this.btnExit.onHoverState.IconRightImage = null;
            this.btnExit.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(15)))), ((int)(((byte)(15)))));
            this.btnExit.OnIdleState.BorderRadius = 1;
            this.btnExit.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExit.OnIdleState.BorderThickness = 1;
            this.btnExit.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(15)))), ((int)(((byte)(15)))));
            this.btnExit.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnExit.OnIdleState.IconLeftImage = null;
            this.btnExit.OnIdleState.IconRightImage = null;
            this.btnExit.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(32)))), ((int)(((byte)(32)))));
            this.btnExit.OnPressedState.BorderRadius = 1;
            this.btnExit.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExit.OnPressedState.BorderThickness = 1;
            this.btnExit.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(176)))), ((int)(((byte)(32)))), ((int)(((byte)(32)))));
            this.btnExit.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnExit.OnPressedState.IconLeftImage = null;
            this.btnExit.OnPressedState.IconRightImage = null;
            this.btnExit.Size = new System.Drawing.Size(50, 30);
            this.btnExit.TabIndex = 6;
            this.btnExit.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnExit.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnExit.TextMarginLeft = 0;
            this.btnExit.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnExit.UseDefaultRadiusAndThickness = true;
            this.btnExit.Click += new System.EventHandler(this.btnExit_Click);
            // 
            // dragControlHeadBar
            // 
            this.dragControlHeadBar.Fixed = true;
            this.dragControlHeadBar.Horizontal = true;
            this.dragControlHeadBar.TargetControl = this.pnlHeadBar;
            this.dragControlHeadBar.Vertical = true;
            // 
            // dragControlLogo
            // 
            this.dragControlLogo.Fixed = true;
            this.dragControlLogo.Horizontal = true;
            this.dragControlLogo.TargetControl = this.pnlLeftImage;
            this.dragControlLogo.Vertical = true;
            // 
            // dragControlResim
            // 
            this.dragControlResim.Fixed = true;
            this.dragControlResim.Horizontal = true;
            this.dragControlResim.TargetControl = this.pbLogo;
            this.dragControlResim.Vertical = true;
            // 
            // PageMain
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1280, 768);
            this.Controls.Add(this.bunifuPanel1);
            this.Controls.Add(this.pnlHeadBar);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "PageMain";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Yummy Day | Restoran Menüsü";
            this.Shown += new System.EventHandler(this.PageMain_Shown);
            this.pnlHeadBar.ResumeLayout(false);
            this.bunifuPanel1.ResumeLayout(false);
            this.pnlLeft.ResumeLayout(false);
            this.pnlLeftImage.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pbLogo)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel pnlHeadBar;
        private Bunifu.UI.WinForms.BunifuPanel pnlLeft;
        private Bunifu.UI.WinForms.BunifuPanel pnlLeftImage;
        private Bunifu.UI.WinForms.BunifuPictureBox pbLogo;
        private Bunifu.UI.WinForms.BunifuPanel pnlTopColorBar;
        private Bunifu.UI.WinForms.BunifuLabel lblYonetimBar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnExit;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuPanel pnlLastOrders;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnEtYemekleri;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnMakarnalar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCorbalar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSebzeYemekleri;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnIcecekler;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSalatalar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnTatlilar;
        private System.Windows.Forms.Panel pnlMain;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSepet;
        private Bunifu.Framework.UI.BunifuDragControl dragControlHeadBar;
        private Bunifu.Framework.UI.BunifuDragControl dragControlLogo;
        private Bunifu.Framework.UI.BunifuDragControl dragControlResim;
    }
}

